name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, 3.2]
    name: ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: ruby --verbose run.rb
      env:
        SEQUEL_URL: 'postgres://postgres:postgres@localhost/test'
